[project]
name = "scam-detection-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "huggingface-hub>=0.36.2",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.4.1",
    "langchain-core>=0.3.79",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=0.3.11",
    "optimum[onnxruntime]>=1.16.0",
    "pandas",
    "pydantic-settings>=2.13.1",
    "rapidfuzz>=3.14.5",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.5.0",
    "tldextract",
    "torch",
    "transformers>=4.40.0",
    "uvicorn",
    "xgboost",
]
[tool.fastapi]
entrypoint = "backend.main:app"
