[project]
name = "scam-detection-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]",
    "optimum[onnxruntime]>=1.16.0",
    "pydantic-settings>=2.13.1",
    "torch",
    "transformers>=4.40.0",
    "uvicorn",
]
[tool.fastapi]
entrypoint = "backend.main:app"
